import { Drug } from "./db";

export const SEED_DRUGS: Omit<Drug, "id" | "created_at">[] = [
  // Healthy Stock
  {
    name: "Amoxicillin 500mg",
    generic_name: "Amoxicillin Trihydrate",
    category: "Prescription",
    form: "Capsule",
    barcode: "600123456789",
    stock: 150,
    price: 450,
    cost_price: 310,
    unit: "pcs",
    manufacturer: "GSK Pharmaceuticals",
    description: "Broad-spectrum antibiotic for bacterial infections.",
    expiry_date: "2027-12-31",
    low_stock_threshold: 20,
    prescription_required: true,
    is_taxable: false,
    batch_number: "AMX-774-B",
    is_active: true
  },
  {
    name: "Panadol Advance",
    generic_name: "Paracetamol",
    category: "OTC",
    form: "Tablet",
    barcode: "600987654321",
    stock: 500,
    price: 15,
    cost_price: 8,
    unit: "pcs",
    manufacturer: "Haleon",
    description: "Fast-acting pain relief and fever reduction.",
    expiry_date: "2026-06-15",
    low_stock_threshold: 50,
    prescription_required: false,
    is_taxable: true,
    batch_number: "PN-992-A",
    is_active: true
  },
  {
    name: "Insulin Glargine",
    generic_name: "Lantus",
    category: "Prescription",
    form: "Injection",
    barcode: "600456789123",
    stock: 45,
    price: 2800,
    cost_price: 2100,
    unit: "vial",
    manufacturer: "Sanofi",
    description: "Long-acting basal insulin for diabetes management. KEEP REFRIGERATED.",
    expiry_date: "2026-12-01",
    low_stock_threshold: 10,
    prescription_required: true,
    is_taxable: false,
    batch_number: "INS-001-L",
    is_active: true
  },
  {
    name: "Cetirizine 10mg",
    generic_name: "Zyrtec",
    category: "OTC",
    form: "Tablet",
    barcode: "600321654987",
    stock: 200,
    price: 30,
    cost_price: 12,
    unit: "pcs",
    manufacturer: "UCB Pharma",
    description: "Second-generation antihistamine for allergy relief.",
    expiry_date: "2027-03-20",
    low_stock_threshold: 30,
    prescription_required: false,
    is_taxable: true,
    batch_number: "CET-443-P",
    is_active: true
  },
  {
    name: "Augmentin 625mg",
    generic_name: "Co-amoxiclav",
    category: "Prescription",
    form: "Tablet",
    barcode: "600789123456",
    stock: 80,
    price: 1200,
    cost_price: 850,
    unit: "box",
    manufacturer: "GSK",
    description: "Combination antibiotic for resistant infections.",
    expiry_date: "2026-09-10",
    low_stock_threshold: 15,
    prescription_required: true,
    is_taxable: false,
    batch_number: "AUG-112-X",
    is_active: true
  },

  // Low Stock
  {
    name: "Ventolin Inhaler",
    generic_name: "Salbutamol",
    category: "Prescription",
    form: "Inhaler",
    barcode: "600159357482",
    stock: 4,
    price: 850,
    cost_price: 600,
    unit: "unit",
    manufacturer: "GSK",
    description: "Short-acting beta-2 agonist for asthma relief.",
    expiry_date: "2026-01-15",
    low_stock_threshold: 10,
    prescription_required: true,
    is_taxable: false,
    batch_number: "VEN-883-M",
    is_active: true
  },
  {
    name: "Aspirin 75mg",
    generic_name: "Ecotrin",
    category: "OTC",
    form: "Tablet",
    barcode: "600258147369",
    stock: 8,
    price: 5,
    cost_price: 2,
    unit: "pcs",
    manufacturer: "Aspen",
    description: "Low-dose aspirin for cardiovascular protection.",
    expiry_date: "2026-04-30",
    low_stock_threshold: 20,
    prescription_required: false,
    is_taxable: true,
    batch_number: "ASP-002-Z",
    is_active: true
  },

  // Out of Stock (Finished)
  {
    name: "Artemether/Lumefantrine",
    generic_name: "Coartem",
    category: "Prescription",
    form: "Tablet",
    barcode: "600369852147",
    stock: 0,
    price: 650,
    cost_price: 400,
    unit: "dose",
    manufacturer: "Novartis",
    description: "First-line treatment for uncomplicated malaria.",
    expiry_date: "2026-11-20",
    low_stock_threshold: 10,
    prescription_required: true,
    is_taxable: false,
    batch_number: "COA-551-Q",
    is_active: true
  },
  {
    name: "Omeprazole 20mg",
    generic_name: "Losec",
    category: "OTC",
    form: "Capsule",
    barcode: "600147258369",
    stock: 0,
    price: 50,
    cost_price: 18,
    unit: "pcs",
    manufacturer: "AstraZeneca",
    description: "Proton pump inhibitor for acid reflux/ulcers.",
    expiry_date: "2027-01-01",
    low_stock_threshold: 50,
    prescription_required: false,
    is_taxable: true,
    batch_number: "OMP-990-W",
    is_active: true
  },

  // Expired
  {
    name: "Metformin 500mg",
    generic_name: "Glucophage",
    category: "Prescription",
    form: "Tablet",
    barcode: "600951753468",
    stock: 120,
    price: 200,
    cost_price: 80,
    unit: "pcs",
    manufacturer: "Merck",
    description: "Oral antidiabetic medication for Type 2 diabetes.",
    expiry_date: "2024-03-01",
    low_stock_threshold: 30,
    prescription_required: true,
    is_taxable: false,
    batch_number: "MET-332-E",
    is_active: true
  },
  {
    name: "Eye Drops (Normal Saline)",
    generic_name: "Saline",
    category: "OTC",
    form: "Syrup",
    barcode: "600753159482",
    stock: 15,
    price: 350,
    cost_price: 150,
    unit: "bottle",
    manufacturer: "Local Pharma",
    description: "Sterile saline solution for eye irrigation.",
    expiry_date: "2025-01-15",
    low_stock_threshold: 5,
    prescription_required: false,
    is_taxable: true,
    batch_number: "EYE-001-S",
    is_active: true
  },

  // More Professional Meds
  {
    name: "Azithromycin 500mg",
    generic_name: "Zithromax",
    category: "Prescription",
    form: "Tablet",
    barcode: "600852963741",
    stock: 60,
    price: 1500,
    cost_price: 900,
    unit: "box",
    manufacturer: "Pfizer",
    description: "Macrolide antibiotic for respiratory infections.",
    expiry_date: "2027-05-30",
    low_stock_threshold: 10,
    prescription_required: true,
    is_taxable: false,
    batch_number: "AZI-221-Y",
    is_active: true
  },
  {
    name: "Amlodipine 5mg",
    generic_name: "Norvasc",
    category: "Prescription",
    form: "Tablet",
    barcode: "600741852963",
    stock: 180,
    price: 45,
    cost_price: 15,
    unit: "pcs",
    manufacturer: "Pfizer",
    description: "Calcium channel blocker for hypertension.",
    expiry_date: "2027-10-15",
    low_stock_threshold: 30,
    prescription_required: true,
    is_taxable: false,
    batch_number: "AML-004-K",
    is_active: true
  },
  {
    name: "Multivitamin Syrup",
    generic_name: "Pediavit",
    category: "Supplement",
    form: "Syrup",
    barcode: "600963852741",
    stock: 25,
    price: 550,
    cost_price: 380,
    unit: "bottle",
    manufacturer: "VitaPharma",
    description: "Essential vitamins for pediatric growth support.",
    expiry_date: "2026-08-20",
    low_stock_threshold: 5,
    prescription_required: false,
    is_taxable: true,
    batch_number: "VIT-667-H",
    is_active: true
  },
  {
    name: "Hydrocortisone Cream",
    generic_name: "Cortizone",
    category: "OTC",
    form: "Cream",
    barcode: "600123789456",
    stock: 40,
    price: 450,
    cost_price: 280,
    unit: "tube",
    manufacturer: "Bayer",
    description: "Mild topical steroid for skin inflammation.",
    expiry_date: "2026-11-30",
    low_stock_threshold: 10,
    prescription_required: false,
    is_taxable: true,
    batch_number: "HYD-111-U",
    is_active: true
  },
  {
    name: "Vitamin C 500mg",
    generic_name: "Ascorbic Acid",
    category: "Supplement",
    form: "Tablet",
    barcode: "600321789654",
    stock: 300,
    price: 10,
    cost_price: 4,
    unit: "pcs",
    manufacturer: "Local Meds",
    description: "Immune system support and antioxidant.",
    expiry_date: "2027-12-01",
    low_stock_threshold: 50,
    prescription_required: false,
    is_taxable: true,
    batch_number: "VIC-889-J",
    is_active: true
  },
  {
    name: "Diclofenac Gel",
    generic_name: "Voltaren",
    category: "OTC",
    form: "Cream",
    barcode: "600654321987",
    stock: 55,
    price: 750,
    cost_price: 520,
    unit: "tube",
    manufacturer: "GSK",
    description: "Topical NSAID for joint and muscle pain.",
    expiry_date: "2026-07-15",
    low_stock_threshold: 10,
    prescription_required: false,
    is_taxable: true,
    batch_number: "DIC-442-R",
    is_active: true
  },
  {
    name: "Warfarin 5mg",
    generic_name: "Coumadin",
    category: "Prescription",
    form: "Tablet",
    barcode: "600987123654",
    stock: 12,
    price: 40,
    cost_price: 25,
    unit: "pcs",
    manufacturer: "Bristol-Myers",
    description: "Anticoagulant for blood clot prevention. HIGH ALERT.",
    expiry_date: "2026-02-10",
    low_stock_threshold: 20,
    prescription_required: true,
    is_taxable: false,
    batch_number: "WAR-009-T",
    is_active: true
  },
  {
    name: "Oral Rehydration Salts (ORS)",
    generic_name: "Electrolytes",
    category: "OTC",
    form: "Tablet",
    barcode: "600456123789",
    stock: 0,
    price: 100,
    cost_price: 40,
    unit: "sachet",
    manufacturer: "WHO Standard",
    description: "For replacement of fluids/electrolytes in dehydration.",
    expiry_date: "2027-04-01",
    low_stock_threshold: 50,
    prescription_required: false,
    is_taxable: false,
    batch_number: "ORS-112-D",
    is_active: true
  },
  {
    name: "Morphine Sulfate 10mg",
    generic_name: "Morphine",
    category: "Controlled",
    form: "Tablet",
    barcode: "600159753248",
    stock: 25,
    price: 500,
    cost_price: 300,
    unit: "pcs",
    manufacturer: "Special Ops Pharma",
    description: "Strong opioid analgesic. CONTROLLED SUBSTANCE.",
    expiry_date: "2026-10-30",
    low_stock_threshold: 5,
    prescription_required: true,
    is_taxable: false,
    batch_number: "MOR-993-S",
    is_active: true
  },
  {
    name: "Ciprofloxacin 500mg",
    generic_name: "Cipro",
    category: "Prescription",
    form: "Tablet",
    barcode: "600111222333",
    stock: 120,
    price: 350,
    cost_price: 210,
    unit: "pcs",
    manufacturer: "Bayer",
    description: "Fluoroquinolone antibiotic for urinary and chest infections.",
    expiry_date: "2027-02-15",
    low_stock_threshold: 30,
    prescription_required: true,
    is_taxable: false,
    batch_number: "CIP-441-V",
    is_active: true
  },
  {
    name: "Metronidazole 400mg",
    generic_name: "Flagyl",
    category: "Prescription",
    form: "Tablet",
    barcode: "600444555666",
    stock: 180,
    price: 250,
    cost_price: 140,
    unit: "pcs",
    manufacturer: "Sanofi",
    description: "Antibiotic and antiprotozoal medication.",
    expiry_date: "2026-09-20",
    low_stock_threshold: 40,
    prescription_required: true,
    is_taxable: false,
    batch_number: "MET-112-D",
    is_active: true
  },
  {
    name: "Gaviscon Advance",
    generic_name: "Sodium Alginate",
    category: "OTC",
    form: "Syrup",
    barcode: "600777888999",
    stock: 45,
    price: 950,
    cost_price: 680,
    unit: "bottle",
    manufacturer: "Reckitt",
    description: "Fast relief from heartburn and acid indigestion.",
    expiry_date: "2026-12-30",
    low_stock_threshold: 10,
    prescription_required: false,
    is_taxable: true,
    batch_number: "GAV-002-X",
    is_active: true
  },
  {
    name: "Prednisone 5mg",
    generic_name: "Deltacortril",
    category: "Prescription",
    form: "Tablet",
    barcode: "600222111333",
    stock: 300,
    price: 15,
    cost_price: 6,
    unit: "pcs",
    manufacturer: "Pfizer",
    description: "Corticosteroid for inflammation and allergic conditions.",
    expiry_date: "2027-04-10",
    low_stock_threshold: 50,
    prescription_required: true,
    is_taxable: false,
    batch_number: "PRE-551-M",
    is_active: true
  },
  {
    name: "Furosemide 40mg",
    generic_name: "Lasix",
    category: "Prescription",
    form: "Tablet",
    barcode: "600888999111",
    stock: 400,
    price: 12,
    cost_price: 4,
    unit: "pcs",
    manufacturer: "Sanofi",
    description: "Loop diuretic for edema and hypertension.",
    expiry_date: "2027-01-20",
    low_stock_threshold: 100,
    prescription_required: true,
    is_taxable: false,
    batch_number: "FUR-992-K",
    is_active: true
  },
  {
    name: "Atenolol 50mg",
    generic_name: "Tenormin",
    category: "Prescription",
    form: "Tablet",
    barcode: "600333222111",
    stock: 150,
    price: 60,
    cost_price: 25,
    unit: "pcs",
    manufacturer: "AstraZeneca",
    description: "Beta-blocker for hypertension and angina.",
    expiry_date: "2026-11-05",
    low_stock_threshold: 30,
    prescription_required: true,
    is_taxable: false,
    batch_number: "ATE-441-L",
    is_active: true
  },
  {
    name: "Diazepam 5mg",
    generic_name: "Valium",
    category: "Controlled",
    form: "Tablet",
    barcode: "600666555444",
    stock: 50,
    price: 80,
    cost_price: 45,
    unit: "pcs",
    manufacturer: "Roche",
    description: "Benzodiazepine for anxiety and seizures. CONTROLLED.",
    expiry_date: "2025-12-01",
    low_stock_threshold: 10,
    prescription_required: true,
    is_taxable: false,
    batch_number: "DIA-001-C",
    is_active: true
  },
  {
    name: "Povidone Iodine 100ml",
    generic_name: "Betadine",
    category: "OTC",
    form: "Cream",
    barcode: "600555444333",
    stock: 60,
    price: 450,
    cost_price: 280,
    unit: "bottle",
    manufacturer: "Mundipharma",
    description: "Antiseptic solution for wound care and surgery.",
    expiry_date: "2027-08-15",
    low_stock_threshold: 15,
    prescription_required: false,
    is_taxable: true,
    batch_number: "POV-221-W",
    is_active: true
  },
  {
    name: "Elastic Bandage 10cm",
    generic_name: "Crepe Bandage",
    category: "OTC",
    form: "Cream",
    barcode: "600999000111",
    stock: 100,
    price: 250,
    cost_price: 150,
    unit: "unit",
    manufacturer: "Medisupply",
    description: "Compression bandage for sprains and supports.",
    expiry_date: "2030-01-01",
    low_stock_threshold: 20,
    prescription_required: false,
    is_taxable: true,
    batch_number: "BAN-881-Q",
    is_active: true
  },
  {
    name: "Latex Gloves (Box 100)",
    generic_name: "Examination Gloves",
    category: "OTC",
    form: "Capsule",
    barcode: "600000111222",
    stock: 30,
    price: 1200,
    cost_price: 850,
    unit: "box",
    manufacturer: "SafeTouch",
    description: "Non-sterile latex gloves for medical use.",
    expiry_date: "2028-01-01",
    low_stock_threshold: 5,
    prescription_required: false,
    is_taxable: true,
    batch_number: "GLO-001-A",
    is_active: true
  },
  {
    name: "Clotrimazole 1%",
    generic_name: "Canesten",
    category: "OTC",
    form: "Cream",
    barcode: "600333444555",
    stock: 75,
    price: 650,
    cost_price: 420,
    unit: "tube",
    manufacturer: "Bayer",
    description: "Broad-spectrum antifungal cream for skin infections.",
    expiry_date: "2026-10-15",
    low_stock_threshold: 15,
    prescription_required: false,
    is_taxable: true,
    batch_number: "CLO-771-K",
    is_active: true
  },
  {
    name: "Vitamin B Complex",
    generic_name: "Neurobion",
    category: "Supplement",
    form: "Tablet",
    barcode: "600666777888",
    stock: 250,
    price: 25,
    cost_price: 12,
    unit: "pcs",
    manufacturer: "P&G",
    description: "Nerve support and energy metabolism booster.",
    expiry_date: "2027-06-30",
    low_stock_threshold: 50,
    prescription_required: false,
    is_taxable: true,
    batch_number: "VIB-442-R",
    is_active: true
  },
  {
    name: "Ferrous Sulfate 200mg",
    generic_name: "Iron Tablets",
    category: "Supplement",
    form: "Tablet",
    barcode: "600444333222",
    stock: 400,
    price: 8,
    cost_price: 3,
    unit: "pcs",
    manufacturer: "Global Health",
    description: "Iron supplement for nutritional anemia.",
    expiry_date: "2027-03-15",
    low_stock_threshold: 100,
    prescription_required: false,
    is_taxable: false,
    batch_number: "FER-001-I",
    is_active: true
  },
  {
    name: "Folic Acid 5mg",
    generic_name: "Folvite",
    category: "Supplement",
    form: "Tablet",
    barcode: "600111000999",
    stock: 500,
    price: 5,
    cost_price: 2,
    unit: "pcs",
    manufacturer: "Pfizer",
    description: "Essential B-vitamin for pregnancy and cell health.",
    expiry_date: "2027-12-31",
    low_stock_threshold: 100,
    prescription_required: false,
    is_taxable: false,
    batch_number: "FOL-991-P",
    is_active: true
  },
  {
    name: "Ventolin Syrup 100ml",
    generic_name: "Salbutamol Syrup",
    category: "Prescription",
    form: "Syrup",
    barcode: "600888777666",
    stock: 40,
    price: 450,
    cost_price: 310,
    unit: "bottle",
    manufacturer: "GSK",
    description: "Bronchodilator syrup for pediatric respiratory relief.",
    expiry_date: "2026-05-20",
    low_stock_threshold: 10,
    prescription_required: true,
    is_taxable: false,
    batch_number: "VES-115-H",
    is_active: true
  },
  {
    name: "Enoxaparin 40mg",
    generic_name: "Clexane",
    category: "Prescription",
    form: "Injection",
    barcode: "600222333444",
    stock: 20,
    price: 1500,
    cost_price: 1100,
    unit: "injection",
    manufacturer: "Sanofi",
    description: "Low molecular weight heparin for thrombosis prevention.",
    expiry_date: "2026-03-15",
    low_stock_threshold: 5,
    prescription_required: true,
    is_taxable: false,
    batch_number: "ENO-002-S",
    is_active: true
  },
  {
    name: "Zinc Sulfate 20mg",
    generic_name: "Zinc",
    category: "Supplement",
    form: "Tablet",
    barcode: "600444555111",
    stock: 120,
    price: 15,
    cost_price: 6,
    unit: "pcs",
    manufacturer: "NutraLocal",
    description: "Zinc supplement for diarrhea management and immunity.",
    expiry_date: "2026-11-30",
    low_stock_threshold: 20,
    prescription_required: false,
    is_taxable: true,
    batch_number: "ZIN-889-Z",
    is_active: true
  },
  {
    name: "Bisacodyl 5mg",
    generic_name: "Dulcolax",
    category: "OTC",
    form: "Tablet",
    barcode: "600111555999",
    stock: 200,
    price: 20,
    cost_price: 9,
    unit: "pcs",
    manufacturer: "Boehringer",
    description: "Stimulant laxative for constipation relief.",
    expiry_date: "2027-01-10",
    low_stock_threshold: 30,
    prescription_required: false,
    is_taxable: true,
    batch_number: "BIS-002-C",
    is_active: true
  },
  {
    name: "Tamsulosin 0.4mg",
    generic_name: "Flomax",
    category: "Prescription",
    form: "Capsule",
    barcode: "600777333111",
    stock: 90,
    price: 1200,
    cost_price: 850,
    unit: "box",
    manufacturer: "Astellas",
    description: "Alpha-blocker for BPH (Prostate) symptoms.",
    expiry_date: "2026-12-15",
    low_stock_threshold: 15,
    prescription_required: true,
    is_taxable: false,
    batch_number: "TAM-443-B",
    is_active: true
  },
  {
    name: "Loperamide 2mg",
    generic_name: "Imodium",
    category: "OTC",
    form: "Capsule",
    barcode: "600222000888",
    stock: 150,
    price: 10,
    cost_price: 4,
    unit: "pcs",
    manufacturer: "J&J",
    description: "Anti-diarrheal medication for symptom relief.",
    expiry_date: "2027-09-01",
    low_stock_threshold: 30,
    prescription_required: false,
    is_taxable: true,
    batch_number: "LOP-111-H",
    is_active: true
  }
];
